env: "dev"
storage_path: "storage/storage.db"
http_server:
  address: "localhost:8082"
database:
  host: "localhost"         
  port: 5432
  user: "postgres"          
  password: "yourpassword"   
  dbname: "student_db"
  sslmode: "disable"